steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tone-toner:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tone-toner:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'tone-toner'
    - '--image'
    - 'gcr.io/$PROJECT_ID/tone-toner:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'API_KEY=$$API_KEY,SECRET_KEY=$$SECRET_KEY'

substitutions:
  _API_KEY: '${_API_KEY}'
  _SECRET_KEY: '${_SECRET_KEY}'

options:
  substitution_option: 'ALLOW_LOOSE'
